### ISSUE TITLE
Account Delete Function

### ISSUE THREAD

**Issue by eather009** [lightoj-dev/problem-tutorials#110]
Hi! 

Accidentally I have created a duplicate account for myself with two emails. I want to delete one of my accounts. If there have such an option to delete an account, that will help to keep a single account with a single `user handle`.

Thank you

**Comment by faiyaz26** [comment]
First this repo is not the right place for this kind of issue. Check this one https://github.com/lightoj-dev/bugs-and-features/issues

And we don't have any account deletion or merge feature, will not have in foreseeable future.
