### ISSUE TITLE
LOJ - 1014: Code gets WA for samples

### ISSUE THREAD

**Issue by inzamam-inz** [lightoj-dev/problem-tutorials#111]
This [editorial's code](https://github.com/lightoj-dev/problem-tutorials/blob/main/1014/en.md?fbclid=IwAR1ubSjv5PiCdII0jJijhmvhvo-z_iveBb_1brl0l-H5eMJaDTMTGu-sbwA) can't pass sample test case of [Iftar Party](https://lightoj.com/problem/1014) problem.
@rebornplusplus

**Comment by rebornplusplus** [comment]
![image](https://user-images.githubusercontent.com/18555205/104120572-0a525380-5362-11eb-8125-84b7c27f46f9.png)

True. @ar-pavel please check.

**Comment by ar-pavel** [comment]
#113
