### ISSUE TITLE
Images attached by relative linking via html are not showing up in the platform.

### ISSUE THREAD

**Issue by showrav-ansary** [lightoj-dev/problem-tutorials#171]
Hi. The images attached to solutions are missing in *some* LightOJ tutorials. Relative linking via html is not working (for example : 1216 https://lightoj.com/problem/juice-in-the-glass) while linking via pure markdown (for example : 1072 https://lightoj.com/problem/calm-down) is working. Will there be a patch to read html as well or tutorials need to corrected to use raw markdown only?

**Comment by faiyaz26** [comment]
Hey, thanks for reporting, I know what is the issue, will fix it soon. In future please use the markdown syntax for displaying image.

**Comment by showrav-ansary** [comment]
Thank you for the guidance.

**Comment by faiyaz26** [comment]
Fixed.
