### ISSUE TITLE
1375 - LCM Extreme (Editorial)

### ISSUE THREAD

**Issue by RobinHood3082** [lightoj-dev/problem-tutorials#201]

**Comment by RobinHood3082** [comment]
Can't assign myself :3

**Comment by showrav-ansary** [comment]
@RobinHood3082 Dear contributor, you have been assigned! Eagerly waiting for your contribution ❤️

**Comment by showrav-ansary** [comment]
@RobinHood3082 Hi. Any update on this?

**Comment by RobinHood3082** [comment]
Sorry I couldn't manage time for this, I will submit it in a week in sha Allah

**Comment by RobinHood3082** [comment]
submitted, link with pull request #226

**Comment by RobinHood3082** [comment]
please check pull request #226
