### ISSUE TITLE
1009 - Back to the underworld (Editorial)

### ISSUE THREAD

**Issue by sakib3201** [lightoj-dev/problem-tutorials#206]
I would like to contribute the English editorial of lightoj-1009 (Back to the Underwold) problem. I have already written most of the editorial , just need to find a few good tutorial. Would be great if I am assigned to this.

**Comment by showrav-ansary** [comment]
@sakib3201 Dear contributor, you have been assigned! 👍🏾

**Comment by sakib3201** [comment]
Done with the editorial (#207 ) waiting for review.
