### ISSUE TITLE
LOJ-1094 (Farthest Nodes in a Tree) Editorial

### ISSUE THREAD

**Issue by sakib3201** [lightoj-dev/problem-tutorials#211]
I would like to start working on the English tutorial of **LOJ-1094 (Farthest Nodes in a Tree)** problem. I have solved it before. I just need to find some good relative resources and create the illustrations. Hopefully it will be done in 2-3 days.

**Comment by showrav-ansary** [comment]
@sakib3201 Dear contributor, you have been assigned! 👍🏾
