### ISSUE TITLE
Formatting Error

### ISSUE THREAD

**Issue by shas9** [lightoj-dev/problem-tutorials#243]
Problem Link: https://lightoj.com/problem/rip-van-winkle-s-code
The input section might have a little latex error. 

![image](https://user-images.githubusercontent.com/53976819/115286537-fd1edf00-a170-11eb-8c56-39843be328b8.png)

**Comment by rebornplusplus** [comment]
Report here: https://github.com/lightoj-dev/bugs-and-features
