### ISSUE TITLE
Add tutorial for LOJ-1348 : Aladdin and the Return Journey

### ISSUE THREAD

**Issue by RaiyaN-98** [lightoj-dev/problem-tutorials#291]

**Comment by rebornplusplus** [comment]
Any updates on this @RaiyaN-98 ?

**Comment by RaiyaN-98** [comment]
I am close to solve the problem but getting TLE for two of the test cases. But yet to figure out the problem of my code. I am still working on it. @rebornplusplus

**Comment by RaiyaN-98** [comment]
I couldn't find the reason behind TLE.

**Comment by rebornplusplus** [comment]
No sweat.
Out of curiosity, what was your approach?

**Comment by RaiyaN-98** [comment]
I used Heavy Light Decomposition. But not sure what is the bug in my code.
