### ISSUE TITLE
LightOj compilation is not working. pending problem

### ISSUE THREAD

**Issue by easeen41** [lightoj-dev/problem-tutorials#336]

**Comment by showrav-ansary** [comment]
@easeen41 Hello dear. Thank you for reporting. The problem will be addressed soon.

**Comment by faiyaz26** [comment]
Thanks for notifying though this is not the right repository for reporting this kind of stuff. From next time please use this repository: https://github.com/lightoj-dev/bugs-and-features

And we have fixed it, we have quite a lot submissions in the backlog, so it will take 30 minutes from now to finish all the queued submissions.
