### ISSUE TITLE
Tutorial for Lightoj 1062 - Crossed Ladders

### ISSUE THREAD

**Issue by ssavi-ict** [lightoj-dev/problem-tutorials#35]
Tutorial for Problem: [http://www.lightoj.com/volume_showproblem.php?problem=1062]( http://www.lightoj.com/volume_showproblem.php?problem=1062)
Creating PR now.

**Comment by ssavi-ict** [comment]
Tutorial for Problem: [http://www.lightoj.com/volume_showproblem.php?problem=1062]( http://www.lightoj.com/volume_showproblem.php?problem=1062)
Creating PR now.

**Comment by ssavi-ict** [comment]
I am about to push to create a PR. it says permission denied. I have tried with my own repos. They are OK.

**Comment by faiyaz26** [comment]
You need to create pull request. Learn about it from here: https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by ssavi-ict** [comment]
Check this PR: https://github.com/lightoj-dev/problem-tutorials/pull/42

**Comment by ssavi-ict** [comment]
![1](https://user-images.githubusercontent.com/14172268/100465297-3e96eb00-30f9-11eb-9319-aeb3ef3653fb.png)
![2](https://user-images.githubusercontent.com/14172268/100465309-422a7200-30f9-11eb-904e-ae0af63f16d4.jpg)
![3](https://user-images.githubusercontent.com/14172268/100465313-45256280-30f9-11eb-9096-29935a9f0803.jpg)


Images are commented for further usage at makrdown pages.
