### ISSUE TITLE
permission to push solution to repository

### ISSUE THREAD

**Issue by hieudoan7** [lightoj-dev/problem-tutorials#361]
Hi team, I am working on creating a solution for a problem but couldn't push changes. The remote repository said that:
`ERROR: Permission to lightoj-dev/problem-tutorials.git denied to hieudoan7.
fatal: Could not read from remote repository.`
Could you guide me through this issue.

**Comment by showrav-ansary** [comment]
@hieudoan7 Hell dear, it seems that you are trying to directly commit changes to the original repo. But what you have to do is:
1. Fork the original repo.
2. Clone your own repo (which gets created after you for a repo).
3. Push changes to your repo.
4 Come back to GitHub after pushing the changes to your repo.
5. You will find a option called `Create Pull Request`, click that.

**Comment by hieudoan7** [comment]
Got it, thank you.
