### ISSUE TITLE
Points in Rectangle LOJ-1266

### ISSUE THREAD

**Issue by qubits-fan** [lightoj-dev/problem-tutorials#363]

**Comment by qubits-fan** [comment]
I am writing tutorial for this problem

**Comment by showrav-ansary** [comment]
@qubits-fan sure dear. Please feel free to create a PR after you are done.

**Comment by faiyaz26** [comment]
Anyone can grab this issue and can look into @qubits-fan's PR, we needed some changes but the author is not responding hence making this issue open for grab.

**Comment by rebornplusplus** [comment]
Closed due to inactivity. 
* @qubits-fan: Reopen if you start working on it again.
* others: Create a new issue for 1266.
