### ISSUE TITLE
Tutorial for problem LOJ-1341

### ISSUE THREAD

**Issue by raselmeya94** [lightoj-dev/problem-tutorials#366]

**Comment by sakib3201** [comment]
This problem looks fairly easy. I would like to be assigned to this problem if no one since no one has been assigned yet. I should be able to complete the editorial by next week.

**Comment by raselmeya94** [comment]
It's ok bro..I'm a little busy with the semester exam.you may carry on👍

**Comment by showrav-ansary** [comment]
@sakib3201 You have been assigned, dear.
