### ISSUE TITLE
Tutorial for LOJ-1166: Old Sorting

### ISSUE THREAD

**Issue by sakib3201** [lightoj-dev/problem-tutorials#367]
I have already solved the problem. I will add the tutorial soon if I am assigned to this problem.

problem: [Old Sorting](https://lightoj.com/problem/old-sorting)

**Comment by showrav-ansary** [comment]
@sakib3201 Hell dear, go for it.

**Comment by sakib3201** [comment]
Closing the issue as the editorial has been added and showing on the website.
