### ISSUE TITLE
Typo in statement of problem 1033: Generating Palindromes

### ISSUE THREAD

**Issue by Casio991ms** [lightoj-dev/problem-tutorials#369]
It says, "By definition a string is said to be a palindrome if it does change when get reversed."
But it should be "By definition a string is said to be a palindrome if it does **not** change when get reversed."

**Comment by faiyaz26** [comment]
As @showrav-ansary mentioned, one should report this kind of issue on our other repo. But thanks for reporting it, I have fixed it.
