### ISSUE TITLE
Incorrect Image (Trailing Zeroes (I))

### ISSUE THREAD

**Issue by Atanusaha143** [lightoj-dev/problem-tutorials#377]
Editorial Link : https://github.com/lightoj-dev/problem-tutorials/blob/main/1028/en.md
Explanation : When we divide 39/2 we get 19 not 18.

**Comment by faiyaz26** [comment]
Could you recreate the image and create a PR to resolve the issue?

**Comment by Atanusaha143** [comment]
Created. You can check!
