### ISSUE TITLE
Tutorial in Bengali language 

### ISSUE THREAD

**Issue by walleeva2018** [lightoj-dev/problem-tutorials#378]
If given the permission i could make bengali tutorials for at least 100+ problems within a month , many of them already have tutorials in English though.

**Comment by showrav-ansary** [comment]
@walleeva2018 Hello dear, please feel free to contribute. We will merge.

**Comment by rebornplusplus** [comment]
@walleeva2018 If you are still working on this, propose a PR when you add a new translation or editorial in Bangla. Remember to create individual PRs for each problem.
I am closing this issue since it doesn't help anybody in anyway knowing you want to do _some_ work on _some_ problems.
