### ISSUE TITLE
English Tutorial for LightOJ 1263 - Equalizing Money

### ISSUE THREAD

**Issue by Nahid-Hossain** [lightoj-dev/problem-tutorials#39]

**Comment by Tahanima** [comment]
Hi, 
Are you working on this?

**Comment by Nahid-Hossain** [comment]
Sorry, I'm not working right now but I'll try to write the editorial on Friday or Saturday. Due to my online class and exam, I'm not getting enough time to start.

**Comment by faiyaz26** [comment]
Hello, Any update on this ?

**Comment by rebornplusplus** [comment]
Hello @Nahid-Hossain, any progress on this?

**Comment by rebornplusplus** [comment]
Alright I am closing this. Re-open if you want to work on this.
