### ISSUE TITLE
LOJ 1001 - Opposite Task

### ISSUE THREAD

**Issue by Heisenberg71** [lightoj-dev/problem-tutorials#4]
# LOJ 1001 - Opposite Task

You have given a number `n`. If `n` can be written as addition of two positive integers such as, `n = a+b`  then print the value of `a` and `b`. Any value of `a` and `b` that follow the equation is accepted.

### C
-----
```c
#include <stdio.h>
int main()
{
    int test, num;
    scanf("%d", &test);
    while(test--){
        scanf("%d", &num);
        if(num > 10){
            printf("%d ", 10);
            num = num - 10;
        }
        else printf("0 ");
        printf("%d\n", num);
    }
    return 0;
}

```

**Comment by faiyaz26** [comment]
Read the readme very carefully: https://github.com/lightoj-dev/problem-tutorials/blob/main/README.md

Add the tutorial on the issue will not work, you need to create Pull request, follow the proper structure

**Comment by faiyaz26** [comment]
Hello, are you working on it? Could you raise the pull request ?

**Comment by Tahanima** [comment]
Closing this issue since the relevant pr has already been merged.
