### ISSUE TITLE
Add tutorial for LOJ-1041 Road Construction

### ISSUE THREAD

**Issue by Evan-CSE** [lightoj-dev/problem-tutorials#407]
Would like to write tutorial for this problem

**Comment by Evan-CSE** [comment]
test

**Comment by Evan-CSE** [comment]
@showrav-ansary  Can you help me to upload the tutorial? I can't upload my tutorial. I have seen your instruction but can't understand.

**Comment by Evan-CSE** [comment]
I am not used to github. So the problem arose. I have cloned the repository and tried to push. But it didn't work. May be its permission issue. Can you let me know how I can upload my tutorial? I am not seeing any commit option in this page.

**Comment by showrav-ansary** [comment]
@Evan-CSE Try these dear:
1. Create a `fork`. If you create a `fork`, you will find `Evan-CSE/problem-tutorials` in your repository collections.
2. Clone that forked repo.
3. Push to that forked repo.
4. Create a pull request.
Check this video out : https://www.youtube.com/watch?v=yr6IzOGoMsQ

**Comment by Evan-CSE** [comment]
Dear @showrav-ansary ,
I like to mention you to be informed if all formalities are done from my side to publish the tutorial. Thank you.
