### ISSUE TITLE
Add tutorial for LOJ-1090 : Trailing Zeroes (II)

### ISSUE THREAD

**Issue by bindubritto** [lightoj-dev/problem-tutorials#44]

**Comment by Tahanima** [comment]
Hi, 
Are you working on this?

**Comment by bindubritto** [comment]
Hello Apu,

I planned to do this but for some reason I can't manage enough time to do
it. If somebody else create an issue for this problem, please assign
him/her. And then remove my assignment.

Thank You.

**Comment by faiyaz26** [comment]
Aborted, other people can work on it.
