### ISSUE TITLE
Add 1051 - Good or Bad (English and Bangla tutorial)

### ISSUE THREAD

**Issue by SadiaAfrinPurba** [lightoj-dev/problem-tutorials#52]

**Comment by faiyaz26** [comment]
Hello, are you still working on this ?

**Comment by SadiaAfrinPurba** [comment]
@faiyaz26 yes.

**Comment by iamsaquib2508** [comment]
Hello. Are you still working on it?

**Comment by Tahanima** [comment]
Hello @SadiaAfrinPurba, can you please confirm whether you are working on this?

**Comment by SadiaAfrinPurba** [comment]
Hello, @iamsaquib2508 and @Tahanima, sorry for the late response.  
Yes I'm working on the tutorials. I will create a pull request by 15 January 2021. Is that okay? Or is there any deadline I'm not aware of?

**Comment by Tahanima** [comment]
> Hello, @iamsaquib2508 and @Tahanima, sorry for the late response.
> Yes, I'm working on the tutorials. I will create a pull request by 15 January 2021. Is that okay? Or is there any deadline I'm not aware of?

Yes, it is okay.

**Comment by faiyaz26** [comment]
I am closing this issue. If you want to work on it, reopen it.
