### ISSUE TITLE
Add tutorial for LOJ-1069 : Lift

### ISSUE THREAD

**Issue by Arfaqur-Rahman** [lightoj-dev/problem-tutorials#6]
**[Problem](http://lightoj.com/volume_showproblem.php?problem=1069):** You are given what floor you are on and what floor the lift is on. You need to calculate how many **seconds you will need to get to ground floor**.

_Assume that it takes 4 seconds for the lift to go from any floor to its adjacent floor (up or down). It takes 3 seconds to open or close the door of the lift and you need 5 seconds to enter or exit the lift._

That means you need to calculate the total time, T = time needed by the lift to come to your floor + time needed by the lift door to open + time needed by you to enter the lift  + time needed by the lift door to close + time needed by the lift to reach ground floor + time needed by the lift door to open again + time needed by you to exit the lift.

Here, 
- time needed by the lift to come to your floor = abs(myPosition-liftPosition) * 4sec

- time needed by the lift door to open = 3sec

- time needed by you to enter the lift = 5sec

-  time needed by lift door to close = 3sec

-  time needed by the lift to reach ground floor = myPosition * 4sec

- time needed by the lift door to open again = 3sec

- time needed by you to exit the lift = 5sec

### C++
-----
```c++
#include<bits/stdc++.h>
using namespace std;

int main(){
    int testcase; 
    cin>>testcase;
    
    for(int t=1; t<=testcase; t++){
        int myPosition, liftPosition;
        cin>>myPosition>>liftPosition;
      
        int timeTakenByMeToEnter=5;
        int timeTakenByMeToExit=5;
        int timeTakenByLiftToOpen=3;
        int timeTakenByLiftToClose=3;
        int timeTakenByLiftToReachMyFloor= abs(myPosition-liftPosition)*4; // If lift was on floor 8 and I was on floor 2, (2-8)=-6. To avoid the minus sign, we used the abs() function. As lift takes 4 seconds to reach the adjacent floor, we multiply by 4.
        int timeTakenByLiftToReachGroundFloorFromMyFloor=(myPosition)*4; //Lift takes 4 seconds to go from one floor to the next floor. That's why we multiply by 4.
        
        cout<<"Case "<<t<<": "<<  abs(myPosition-liftPosition)*4 + timeTakenByLiftToOpen + timeTakenByMeToEnter + timeTakenByLiftToClose + (myPosition)*4 + timeTakenByLiftToOpen + timeTakenByMeToExit<<endl;
    }
}
```
Happy Coding!

**Comment by faiyaz26** [comment]
Read the readme very carefully: https://github.com/lightoj-dev/problem-tutorials/blob/main/README.md

Adding the tutorial on the issue will not work, you need to create Pull request, follow the proper structure
