### ISSUE TITLE
Add tutorial for LOJ - 1255 : Substring Frequency

### ISSUE THREAD

**Issue by ihumaunkabir** [lightoj-dev/problem-tutorials#8]

**Comment by faiyaz26** [comment]
Hello, are you working on it?

**Comment by Tahanima** [comment]
Hi @ihumaunkabir 
Please confirm whether you are willing to work on this issue.

**Comment by ihumaunkabir** [comment]
Hi @Tahanima @faiyaz26 

I intended to work on this issue but currently couldn't make it complete. If anyone wants to work on this, please move forward. I'm closing this issue at this moment. I might work on a different problem. 

Thanks.
