### ISSUE TITLE
Add 1186 - Incredible Chess(English tutorial)

### ISSUE THREAD

**Issue by nfpranta** [lightoj-dev/problem-tutorials#97]
Link : http://lightoj.com/volume_showproblem.php?problem=1186

**Comment by rebornplusplus** [comment]
Hello, are you working on this?

**Comment by nfpranta** [comment]
I didn't start working yet.I am a little busy with some other work of mine. If you/someone interested in working on the editorial of this problem, you can.

**Comment by faiyaz26** [comment]
Closing it due to inactivity
